# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HBRestAPIDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
    pod 'YYCategories'
    pod 'OpenSSL-for-iOS', '~> 1.0.2.d.1'
  # Pods for HBRestAPIDemo

end
